In [ ]:
import numpy as np


In [ ]:
!pip install numpy

In [ ]:
twoDList = [[20,30,40],[50,60,70]]

In [ ]:
twoDArray = np.array(twoDList)

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros ([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Linspace here gives output of 5 numbers with equal spacing between each in the range 10 to 100

In [ ]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

Printing 4 ones as float datatypes.

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

Printing 4 ones as integer datatype in a 2D array of 4 rows and 4 columns

In [ ]:
np.ones((4,4),dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

To genrate a random number from 0 to

In [ ]:
np.random.rand()

0.6561783452024457

Printing a sample array , we named the array in a Camle case format ranging from o to the entered range . The arrays prints numbers untill n-1 ; wher n is the entered number.

In [ ]:
sampleArray=np.arange(25)
print(sampleArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


sampleArray.shape

In [ ]:
sampleArray.shape

(25,)

.reshape will change the dimension of the array

In [ ]:
sample2dArray=sampleArray.reshape(5,5)
print(sample2dArray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Gives the maximum value of the 2d Array

In [ ]:
sample2dArray.max()

24

Adds 50 to the previous array (sampleArray)

In [ ]:
sample2dArray = sample2dArray + 50
print(sample2dArray)

[[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]]


Gives the max value of the 2D array (sample2dArray)

In [ ]:
sample2dArray.max()

74

Returns the index value of the max / highest value present in the arrray

In [ ]:
sample2dArray.argmax()

24

Gives the min value of the array (sample2dArray)

In [ ]:
sample2dArray.min()

50

In [ ]:
np.amax(sample2dArray)

74

Addind two arrays using the sumofArray

In [ ]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])
sumofArray = array1 + array2
print(sumofArray)

[ 2  4  6  8 10]


Division of arrays

In [ ]:
array3 = np.array([0,0,0,0,0])

In [ ]:
array1/array3

<ipython-input-41-0e8faa7fc338>:1: RuntimeWarning: divide by zero encountered in divide
  array1/array3


array([inf, inf, inf, inf, inf])

In [ ]:
array3/array1

array([0., 0., 0., 0., 0.])

Reduces all values by 1

In [ ]:
sampleArray[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Changes the vaules on the indexes from 0 to 10 to 10

In [ ]:
sampleArray[0:10]=10

In [ ]:
sampleArray

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])